version: '3.1'

services:

  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
        - ./configuration/alarmdisplay_database.sql:/docker-entrypoint-initdb.d/01.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  alarmdisplay-ffw:
    image: alarmdisplay-ffw:latest
    build:
      context: .
    depends_on:
      - mariadb
    ports:
      - 8888:80
